[versions]
pluginVersion = "0.40"
dynmapApi = "2.1"
bukkit = "1.7.10-R0.1-SNAPSHOT"
citizensApi = "2.0.20-SNAPSHOT"

[libraries]
dynmapApi = { module = "us.dynmap:dynmap-api", version.ref = "dynmapApi" }
bukkit = { module = "org.bukkit:bukkit", version.ref = "bukkit" }
citizensApi = { module = "net.citizensnpcs:citizensapi", version.ref = "citizensApi" }