[versions]
pluginVersion = "0.40"
dynmapCoreApi = "3.8"
spigotApi = "26.3-R0.1-SNAPSHOT"
citizensApi = "2.0.44-SNAPSHOT"

[libraries]
dynmapCoreApi = { module = "us.dynmap:DynmapCoreAPI", version.ref = "dynmapCoreApi" }
spigotApi = { module = "org.spigotmc:spigot-api", version.ref = "spigotApi" }
citizensApi = { module = "net.citizensnpcs:citizensapi", version.ref = "citizensApi" }
